import { ScoringResult } from "./scoring";
import jsPDF from "jspdf";

export async function generateDebriefPDF(results: ScoringResult) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  // Background - Dark Forest Deep
  doc.setFillColor(10, 18, 10); // #0a120a
  doc.rect(0, 0, 210, 297, "F");

  // Border - Wood
  doc.setDrawColor(93, 64, 55); // #5d4037
  doc.setLineWidth(2);
  doc.rect(10, 10, 190, 277);

  // Header
  doc.setTextColor(197, 160, 89); // #c5a059 (Gold)
  doc.setFont("courier", "bold");
  doc.setFontSize(24);
  doc.text("GRAVITY CHECK", 105, 30, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(141, 110, 99); // #8d6e63 (Wood Light)
  doc.text("REBEL OS // SIGNAL REPORT", 105, 38, { align: "center" });

  // Archetype Section
  doc.setTextColor(197, 160, 89);
  doc.setFontSize(12);
  doc.text("DETECTED ORBIT:", 20, 60);
  
  doc.setFontSize(32);
  doc.text(results.archetype, 20, 75);

  doc.setTextColor(230, 200, 133); // #e6c885 (Gold Light)
  doc.setFont("times", "normal");
  doc.setFontSize(14);
  const splitDesc = doc.splitTextToSize(results.description, 170);
  doc.text(splitDesc, 20, 90);

  // Scores Section
  let y = 130;
  doc.setFont("courier", "bold");
  doc.setFontSize(12);
  doc.setTextColor(197, 160, 89);
  doc.text("FLYWHEEL METRICS:", 20, y);
  
  y += 15;
  const metrics = [
    { label: "IDENTITY", value: results.identity },
    { label: "RELATIONSHIP", value: results.relationship },
    { label: "VISION", value: results.vision },
    { label: "CULTURE", value: results.culture }
  ];

  metrics.forEach((m, i) => {
    doc.text(`${m.label}:`, 20, y + (i * 10));
    // Draw bar
    doc.setFillColor(45, 74, 45); // #2d4a2d (Forest Light)
    doc.rect(60, y + (i * 10) - 4, 100, 4, "F");
    doc.setFillColor(197, 160, 89); // Gold
    doc.rect(60, y + (i * 10) - 4, (m.value / 5) * 100, 4, "F");
    doc.text(m.value.toString(), 165, y + (i * 10));
  });

  // Leak Section
  y += 60;
  doc.setFillColor(26, 46, 26); // #1a2e1a (Forest)
  doc.rect(20, y, 170, 30, "F");
  doc.setDrawColor(197, 160, 89);
  doc.rect(20, y, 170, 30);

  doc.setTextColor(127, 29, 29); // #7f1d1d (Destructive Red)
  doc.text(`PRIMARY LEAK: ${results.leak}`, 30, y + 10);
  
  doc.setTextColor(230, 200, 133);
  doc.setFont("times", "normal");
  doc.setFontSize(12);
  const splitLeak = doc.splitTextToSize(results.leakDescription, 150);
  doc.text(splitLeak, 30, y + 20);

  // First Move Section (New)
  y += 40;
  doc.setFillColor(197, 160, 89); // Gold Background
  doc.rect(20, y, 170, 30, "F");
  
  doc.setTextColor(10, 18, 10); // Dark Text
  doc.setFont("courier", "bold");
  doc.text(`PRESCRIPTION: ${results.firstMove}`, 30, y + 10);
  
  doc.setFont("times", "normal");
  const splitMove = doc.splitTextToSize(results.firstMoveDescription, 150);
  doc.text(splitMove, 30, y + 20);

  // Footer
  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  doc.setTextColor(141, 110, 99);
  doc.text("GENERATED BY REBEL-LEADER.COM", 105, 280, { align: "center" });

  doc.save("gravity-check-debrief.pdf");
}
