// Scoring Logic for Gravity Check

export interface ScoringResult {
  identity: number;
  relationship: number;
  vision: number;
  culture: number;
  archetype: string;
  leak: string;
  force: string;
  description: string;
  leakDescription: string;
  forceDescription: string;
}

// Archetype Definitions
const ARCHETYPES = {
  SHATTERED_MOON: {
    name: "SHATTERED MOON",
    description: "High potential energy, but zero cohesion. Your team is a collection of brilliant fragments drifting apart. Without a unifying gravity, you're losing your best people to the void.",
  },
  FRICTION_BELT: {
    name: "FRICTION BELT",
    description: "You're moving, but at a high cost. Every step forward requires disproportionate effort. The heat you feel isn't passion—it's the grinding of structural misalignment.",
  },
  BORROWED_GRAVITY: {
    name: "BORROWED GRAVITY",
    description: "You're orbiting a star that isn't yours—a charismatic leader, a client, or a past success. It works for now, but it's not sustainable. You need to generate your own core pull.",
  },
  FORMING_ORBIT: {
    name: "FORMING ORBIT",
    description: "The pieces are coming together. You have moments of flow and clarity, but they aren't yet the default. You're one or two structural shifts away from a self-sustaining system.",
  },
  STABLE_ORBIT: {
    name: "STABLE ORBIT",
    description: "A rare state of grace. Your culture generates more energy than it consumes. The work is hard, but the friction is low. Your job now is stewardship, not repair.",
  },
};

// Leak Types
const LEAKS = {
  SILENCE_TAX: {
    name: "SILENCE TAX",
    description: "The cost of things unsaid. When truth is withheld to 'keep the peace,' it creates a debt that is eventually paid in resentment and failure.",
  },
  ROLE_FOG: {
    name: "ROLE FOG",
    description: "Energy wasted guessing who owns what. When authority is ambiguous, your best people hesitate instead of acting.",
  },
  MEANING_COLLAPSE: {
    name: "MEANING COLLAPSE",
    description: "The 'why' has evaporated. People are executing tasks but have lost connection to the mission. Burnout is imminent.",
  },
  HERO_SUBSIDY: {
    name: "HERO SUBSIDY",
    description: "Over-reliance on individual heroics to cover for systemic gaps. You're burning out your best people to keep a broken machine running.",
  },
};

// Dominant Forces
const FORCES = {
  GRAVITY: {
    name: "GRAVITY",
    description: "The pull of a compelling vision and shared identity.",
  },
  ENTROPY: {
    name: "ENTROPY",
    description: "The natural tendency toward disorder and disconnection.",
  },
  INERTIA: {
    name: "INERTIA",
    description: "The resistance to change or movement.",
  },
  FRICTION: {
    name: "FRICTION",
    description: "The heat generated by misalignment.",
  },
};

export function calculateScore(answers: Record<number, number>): ScoringResult {
  // 1. Calculate Category Scores (Average of 3 questions per category)
  // Identity: Q1, Q2, Q3
  const identity = ((answers[1] || 0) + (answers[2] || 0) + (answers[3] || 0)) / 3;
  
  // Relationship: Q4, Q5, Q6
  const relationship = ((answers[4] || 0) + (answers[5] || 0) + (answers[6] || 0)) / 3;
  
  // Vision: Q7, Q8, Q9
  const vision = ((answers[7] || 0) + (answers[8] || 0) + (answers[9] || 0)) / 3;
  
  // Culture: Q10, Q11, Q12
  const culture = ((answers[10] || 0) + (answers[11] || 0) + (answers[12] || 0)) / 3;

  // 2. Determine Archetype based on average score and variance
  const average = (identity + relationship + vision + culture) / 4;
  const scores = [identity, relationship, vision, culture];
  const minScore = Math.min(...scores);
  
  let archetype = ARCHETYPES.STABLE_ORBIT;
  
  if (average < 2.5) {
    archetype = ARCHETYPES.SHATTERED_MOON;
  } else if (average < 3.5) {
    // Check for high variance (one strong area masking others)
    if (Math.max(...scores) - minScore > 1.5) {
      archetype = ARCHETYPES.BORROWED_GRAVITY;
    } else {
      archetype = ARCHETYPES.FRICTION_BELT;
    }
  } else if (average < 4.2) {
    archetype = ARCHETYPES.FORMING_ORBIT;
  }

  // 3. Identify Leak (Lowest Score Driver)
  let leak = LEAKS.SILENCE_TAX;
  if (minScore === identity) leak = LEAKS.ROLE_FOG; // Proxy for identity issues
  if (minScore === relationship) leak = LEAKS.SILENCE_TAX;
  if (minScore === vision) leak = LEAKS.MEANING_COLLAPSE;
  if (minScore === culture) leak = LEAKS.HERO_SUBSIDY;

  // 4. Identify Dominant Force
  let force = FORCES.GRAVITY;
  if (archetype === ARCHETYPES.SHATTERED_MOON) force = FORCES.ENTROPY;
  if (archetype === ARCHETYPES.FRICTION_BELT) force = FORCES.FRICTION;
  if (archetype === ARCHETYPES.BORROWED_GRAVITY) force = FORCES.INERTIA;

  return {
    identity: Number(identity.toFixed(1)),
    relationship: Number(relationship.toFixed(1)),
    vision: Number(vision.toFixed(1)),
    culture: Number(culture.toFixed(1)),
    archetype: archetype.name,
    description: archetype.description,
    leak: leak.name,
    leakDescription: leak.description,
    force: force.name,
    forceDescription: force.description,
  };
}
